
name: Build

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
